ROOT=Calendar

all: 
	clang++ ./${ROOT}/*.m -o ./cal -framework Foundation
	@echo "使用:"
	@echo "  命令:"
	@echo "    cal"
	@echo "    cal -m [month]"
	@echo "    cal [month] [year]"
	@echo "    cal [year]"
	@echo "  检查:"
	@echo "    year: 正数"
	@echo "    month: 1-12的正数"
	@echo "  By Marveliu   "
